name: Frontmatter Check

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  check-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gemini CLI
        id: gemini
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini_api_key: "${{ secrets.GEMINI_API_KEY }}"
          prompt: |
            Please check the frontmatter of all posts in the content/posts directory.
            Ensure that each post has:
            - categories (not empty)
            - tags (not empty)
            - date (not empty)
            - emoji (a unique emoji from the list: :sparkles:, :zap:, :star2:, :comet:, :wave:, :sun:, :moon:, :apple:, :banana:, :grapes:, :strawberry:, :watermelon:, :peach:, :pineapple:, :kiwi:, :mango:, :pear:, :melon:, :carrot:, :corn:, :broccoli:, :avocado:, :peanuts:, :chestnut:, :dog:, :cat:, :mouse:, :hamster:, :rabbit:, :fox:, :bear:, :panda_face:, :koala:, :tiger:, :lion_face:, :cow:, :pig:, :frog:, :monkey_face:, :chicken:, :penguin:, :bird:, :baby_chick:, :hatching_chick:, :hatched_chick:, :duck:, :eagle:, :owl:, :bat:, :wolf:, :boar:, :horse:, :unicorn:, :bee:, :bug:, :butterfly:, :snail:, :beetle:, :ant:, :cricket:, :spider:, :scorpion:, :crab:, :snake:, :lizard:, :turtle:, :tropical_fish:, :fish:, :blowfish:, :dolphin:, :whale:, :whale2:, :shark:, :octopus:, :shell:, :seal:, :squid:, :shrimp:, :lobster:, :oyster:, :rooster:, :turkey:, :dove:, :t-rex:, :sauropod:, :dodo:, :flamingo:, :peacock:, :parrot:, :swan:, :poodle:, :racehorse:, :gorilla:, :orangutan:, :sloth:, :otter:, :skunk:, :kangaroo:, :badger:, :giraffe:, :zebra:, :deer:, :rhinoceros:, :hippopotamus:, :elephant:, :camel:, :leopard:, :crocodile:, :tiger2:, :water_buffalo:, :ram:, :goat:, :sheep:, :llama:, :chipmunk:, :hedgehog:, :raccoon:, :rat:, :mouse2:, :dragon:, :dragon_face:, :sauropod:, :t-rex:, :whale:, :whale2:, :dolphin:, :fish:, :tropical_fish:, :blowfish:, :shark:, :octopus:, :shell:, :snail:, :butterfly:, :bug:, :ant:, :bee:, :beetle:, :cricket:, :spider:, :scorpion:, :mosquito:, :fly:, :worm:, :microbe:, :cherry_blossom:, :white_flower:, :rosette:, :rose:, :wilted_rose:, :hibiscus:, :sunflower:, :blossom:, :tulip:, :seedling:, :evergreen_tree:, :deciduous_tree:, :palm_tree:, :cactus:, :ear_of_rice:, :herb:, :shamrock:, :four_leaf_clover:, :maple_leaf:, :fallen_leaf:, :leafy_green:).
            If a post is missing an emoji, add one. Do not use the same emoji twice.
            If any other frontmatter is missing, add it with a placeholder value.
            Then commit the changes.

      - name: Commit files
        if: steps.gemini.outputs.exit_code == 0
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/posts
          git commit -m "chore: update frontmatter"
          git push
          exit 0
