name: Check links

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--verbose --no-progress ./**/*.md ./**/*.html"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
